services:
  app:
    build:
      context: .
    user: "${PUID}:${PGID}"
    volumes:
      - .:/var/www:delegated
      - /var/www/storage
      - /var/www/bootstrap/cache
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      APP_KEY: ${APP_KEY}
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - laravel-network
    depends_on:
      - db
    entrypoint: ["wait-for-it.sh", "db:3306", "--", "/usr/local/bin/docker-entrypoint.sh"]

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel-network
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - laravel-network

volumes:
  db_data:
    driver: local

networks:
  laravel-network:
    driver: bridge